### PR TITLE
propostas para serem verificadas

### PR DESCRIPTION
**Pull request by OclairPrado**

### CODE REVIEW

**Comment by fberanizo** [comment]
É preciso criar um teste unitário para o método:
https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/api.py#L11
Este teste deve estar no arquivo [tests/test_api.py](https://github.com/platiagro/logger/blob/feature/log/tests/test_api.py)

No [README.md](https://github.com/platiagro/logger/tree/feature/log#testing) é explicado como rodar os testes.

**Comment by fberanizo** [comment]
O arquivo api.py.bkp deve ser deletado do versionamento.

**Comment by fberanizo** [comment]
As diretrizes de formatação de código são essas: https://www.python.org/dev/peps/pep-0008/

Ver principalmente esta seção, que trata de nome de funções e variáveis: https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

> Function and Variable Names
Function names should be lowercase, with words separated by underscores as necessary to improve readability.

> Variable names follow the same convention as function names.
> 
> mixedCase is allowed only in contexts where that's already the prevailing style (e.g. threading.py), to retain backwards compatibility.

> Class Names
> Class names should normally use the CapWords convention.

Estes são alguns exemplos de funções e variáveis que deveriam ser ajustadas para o padrão (não listei todos, por gentiliza  verifique tudo):
https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/log.py#L18

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/log.py#L30

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/api.py#L44

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/log.py#L22

**Comment by fberanizo** [comment]
Por favor remover código-fonte comentado:

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/api.py#L2

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/api.py#L58-L62

**Comment by fberanizo** [comment]
Por favor, remover "print" ou trocar por  api.logger.debug. 
Não listei todos, por favor verificar todos arquivos.

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/api.py#L33

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/log.py#L25

**Comment by OclairPrado** [comment]
> O arquivo [api.py.bkp](https://github.com/platiagro/logger/blob/feature/log/logger/api.py.bkp) deve ser deletado do versionamento.

[Oclair] Feito!

**Comment by OclairPrado** [comment]
[Oclair] Feito!

**Comment by fberanizo** [comment]
Também há uma recomendação de não deixar espaços dentro de parênteses:
https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements

> Avoid extraneous whitespace in the following situations:
> 
> Immediately inside parentheses, brackets or braces.
> 
> Yes: spam(ham[1], {eggs: 2})
> No:  spam( ham[ 1 ], { eggs: 2 } )


https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/api.py#L66

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/log.py#L18

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/log.py#L30

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/log.py#L21

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/log.py#L22

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/log.py#L26

**Comment by fberanizo** [comment]
Os parênteses em comandos if/while/for não são necessários (exceto em linhas longas > 80 colunas):

https://github.com/platiagro/logger/blob/e69577241a63eb262af55963ba7f2130c104c4e9/logger/api.py#L46

**Comment by fberanizo** [comment]
Por favor, remover a dependência em comentário:

https://github.com/platiagro/logger/blob/924e8710c3130c7a6c4db7c1ccf6a3bc11658c9f/setup.py#L29

**Pull request merged**
